export const MUSIC_DATA = [
  {
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    genre: "Rock",
    duration: "5:55",
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    genre: "Pop",
    duration: "3:53",
  },
  {
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    genre: "Pop",
    duration: "4:54",
  },
  {
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    genre: "Grunge",
    duration: "5:01",
  },
  {
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    genre: "Soul",
    duration: "3:48",
  },
  {
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    genre: "Rock",
    duration: "6:30",
  },
  {
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Synthpop",
    duration: "3:20",
  },
  {
    title: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
    genre: "Rock",
    duration: "3:03",
  },
  {
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
    genre: "Funk",
    duration: "4:30",
  },
  {
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    genre: "Rock",
    duration: "8:02",
  },
  {
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    genre: "Rock",
    duration: "5:55",
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷ (Divide)",
    genre: "Pop",
    duration: "3:53",
  },
  {
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    genre: "Pop",
    duration: "4:54",
  },
  {
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    album: "Nevermind",
    genre: "Grunge",
    duration: "5:01",
  },
  {
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    genre: "Soul",
    duration: "3:48",
  },
  {
    title: "Hotel California",
    artist: "Eagles",
    album: "Hotel California",
    genre: "Rock",
    duration: "6:30",
  },
  {
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Synthpop",
    duration: "3:20",
  },
  {
    title: "Imagine",
    artist: "John Lennon",
    album: "Imagine",
    genre: "Rock",
    duration: "3:03",
  },
  {
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
    genre: "Funk",
    duration: "4:30",
  },
  {
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    album: "Led Zeppelin IV",
    genre: "Rock",
    duration: "8:02",
  },
];
